"""adiciona momento ao look

Revision ID: 051c5b6e1e9d
Revises: dbdf15f0bd56
Create Date: 2026-09-12 23:04:30.438774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051c5b6e1e9d'
down_revision = 'dbdf15f0bd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('look', schema=None) as batch_op:
        batch_op.add_column(sa.Column('momento', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('look', schema=None) as batch_op:
        batch_op.drop_column('momento')

    # ### end Alembic commands ###
