"""adiciona atribuicao utm ao cliente

Revision ID: 1753e2613a52
Revises: b69dd504f300
Create Date: 2026-08-15 15:33:28.711372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753e2613a52'
down_revision = 'b69dd504f300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_source', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')

    # ### end Alembic commands ###
