"""adiciona foco atual ao cliente

Revision ID: 21b1f5f8922d
Revises: 358548e88e4f
Create Date: 2026-09-13 13:42:44.441427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b1f5f8922d'
down_revision = '358548e88e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foco_atual', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('foco_atual')

    # ### end Alembic commands ###
