"""adiciona pontos chave ao diagnostico estruturado

Revision ID: 358548e88e4f
Revises: a174163d881e
Create Date: 2026-09-13 13:33:01.495249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358548e88e4f'
down_revision = 'a174163d881e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos_chave', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_assessment', schema=None) as batch_op:
        batch_op.drop_column('pontos_chave')

    # ### end Alembic commands ###
