"""adiciona modalidade a consultation

Revision ID: 3e593873665d
Revises: 97c294ed47a2
Create Date: 2026-09-10 15:33:24.231140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e593873665d'
down_revision = '97c294ed47a2'
branch_labels = None
depends_on = None


def upgrade():
    # server_default garante que consultas já existentes recebam
    # 'presencial' (reflete a realidade atual) em vez de falhar por
    # NOT NULL sem valor. Alembic não remove o server_default depois —
    # inofensivo, o modelo já define o default em Python pra inserts novos.
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('modalidade', sa.String(length=20), nullable=False, server_default='presencial')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('modalidade')

    # ### end Alembic commands ###
