"""adiciona look e look_item

Revision ID: 449b2bfe995a
Revises: 517b27109b0d
Create Date: 2026-09-10 13:04:39.261824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449b2bfe995a'
down_revision = '517b27109b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('look',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('ocasiao', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('mensagem_transmitida', sa.String(length=255), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('look_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('look_id', sa.Integer(), nullable=False),
    sa.Column('closet_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['closet_item_id'], ['closet_item.id'], ),
    sa.ForeignKeyConstraint(['look_id'], ['look.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('look_item')
    op.drop_table('look')
    # ### end Alembic commands ###
