"""adiciona campos de identidade visual ao cliente

Revision ID: 517b27109b0d
Revises: 513a8fb082c2
Create Date: 2026-09-10 12:44:50.707371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517b27109b0d'
down_revision = '513a8fb082c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('identidade_rotina', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('identidade_objetivo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('identidade_estilo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('identidade_estilo')
        batch_op.drop_column('identidade_objetivo')
        batch_op.drop_column('identidade_rotina')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('cidade')
        batch_op.drop_column('profissao')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
