"""adiciona embed_url a campaign

Revision ID: 5e64e4c64da1
Revises: b6d023682bc6
Create Date: 2026-08-29 23:21:14.238180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e64e4c64da1'
down_revision = 'b6d023682bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('embed_url')

    # ### end Alembic commands ###
