"""adiciona token de reset de senha ao cliente

Revision ID: 69ff139d9139
Revises: a5d61470fef5
Create Date: 2026-08-29 21:26:00.528786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ff139d9139'
down_revision = 'a5d61470fef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_client_password_reset_token', ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_password_reset_token', type_='unique')
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
