"""adiciona link de compra e foto ao personal shopper

Revision ID: 6cfe41e3d887
Revises: 051c5b6e1e9d
Create Date: 2026-09-12 23:34:46.211925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfe41e3d887'
down_revision = '051c5b6e1e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_compra', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('link_compra')

    # ### end Alembic commands ###
