"""adiciona style_assessment

Revision ID: 745d15c2273d
Revises: 449b2bfe995a
Create Date: 2026-09-10 14:05:13.100783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745d15c2273d'
down_revision = '449b2bfe995a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('estacao_cor', sa.String(length=100), nullable=True),
    sa.Column('paleta_principal', sa.String(length=255), nullable=True),
    sa.Column('estilo_predominante', sa.String(length=100), nullable=True),
    sa.Column('estilo_complementar', sa.String(length=100), nullable=True),
    sa.Column('mensagem_desejada', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_assessment')
    # ### end Alembic commands ###
