"""remove campaign table

Revision ID: 8cc32be0dbb2
Revises: d0d3365a129e
Create Date: 2026-09-10 01:22:02.466059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc32be0dbb2'
down_revision = 'd0d3365a129e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), nullable=False),
    sa.Column('internal_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hero_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('review_note', sa.TEXT(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=False),
    sa.Column('reviewed_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('embed_url', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
