"""adiciona tabela campaign

Revision ID: 96725d9585f7
Revises: 1753e2613a52
Create Date: 2026-08-20 12:10:37.393890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96725d9585f7'
down_revision = '1753e2613a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('internal_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=150), nullable=True),
    sa.Column('hero_title', sa.String(length=255), nullable=False),
    sa.Column('hero_highlight', sa.String(length=100), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=80), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign')
    # ### end Alembic commands ###
