"""adiciona imagens de coloracao ao dossie

Revision ID: a174163d881e
Revises: 6cfe41e3d887
Create Date: 2026-09-13 11:50:26.537282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a174163d881e'
down_revision = '6cfe41e3d887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coloracao_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_report_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['style_report_id'], ['style_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coloracao_image')
    # ### end Alembic commands ###
