"""adiciona login de cliente (password_hash, last_login_at)

Revision ID: a5d61470fef5
Revises: 98b516d2c72a
Create Date: 2026-08-29 20:30:02.796465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d61470fef5'
down_revision = '98b516d2c72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
