"""adiciona arquetipos e pdf_url ao dossie

Revision ID: b6d023682bc6
Revises: bdde5e88ad4e
Create Date: 2026-08-29 22:59:30.502586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d023682bc6'
down_revision = 'bdde5e88ad4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquetipos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_report', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('arquetipos')

    # ### end Alembic commands ###
