"""adiciona campos de servico por dossie ao style report

Revision ID: bdde5e88ad4e
Revises: 69ff139d9139
Create Date: 2026-08-29 21:41:32.611793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde5e88ad4e'
down_revision = '69ff139d9139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estilo_pessoal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proporcoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('coloracao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visagismo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_report', schema=None) as batch_op:
        batch_op.drop_column('visagismo')
        batch_op.drop_column('coloracao')
        batch_op.drop_column('proporcoes')
        batch_op.drop_column('estilo_pessoal')

    # ### end Alembic commands ###
