"""simplifica campaign removendo campos de hero nao essenciais

Revision ID: d0d3365a129e
Revises: 5e64e4c64da1
Create Date: 2026-08-30 12:27:09.765039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d3365a129e'
down_revision = '5e64e4c64da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('hero_eyebrow')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('theme_color')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('hero_highlight')
        batch_op.drop_column('hero_cta_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_cta_text', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('hero_highlight', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('hero_eyebrow', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
