"""adiciona campos preparatorios ao closet item

Revision ID: dbdf15f0bd56
Revises: 97c294ed47a2
Create Date: 2026-09-10 16:56:22.169246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdf15f0bd56'
down_revision = '97c294ed47a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closet_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ocasiao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estilo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closet_item', schema=None) as batch_op:
        batch_op.drop_column('estilo')
        batch_op.drop_column('estacao')
        batch_op.drop_column('ocasiao')
        batch_op.drop_column('marca')
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
