"""adiciona secoes do dossie

Revision ID: f7b37927b951
Revises: 21b1f5f8922d
Create Date: 2026-09-13 23:05:41.136947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b37927b951'
down_revision = '21b1f5f8922d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossie_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_report_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['style_report_id'], ['style_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dossie_section')
    # ### end Alembic commands ###
